// <auto-generated />
namespace A.Core.PermissionModule.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OperationType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OperationType));
        
        string IMigrationMetadata.Id
        {
            get { return "201711012101549_OperationType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
